version: "3.8"

services:

  ########################################################
  # frontend
  ########################################################
  frontend:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000